[package]
name = "uedge"
version = "0.1.0"
authors = ["drasko <drasko.draskovic@gmail.com>"]

[dependencies]
#paho-mqtt = "0.5.0"
paho-mqtt = {path = "/home/drasko/paho.mqtt.rust"}
log = "0.4.6"
env_logger = "0.6.1"

[profile.release]
opt-level = 'z'  # Optimize for size.
lto = true

